# Generated by Django 3.1 on 2020-09-17 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200917_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='user',
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='med_ref',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_reference',
            field=models.UUIDField(default=uuid.UUID('2b6e54b9-959e-4aca-b805-59fa9c064376'), editable=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.UUIDField(default=uuid.UUID('61bdda58-5c14-456a-9fd6-b2a134471b8e'), editable=False),
        ),
        migrations.DeleteModel(
            name='LabTech',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
