# Generated by Django 3.1 on 2020-09-18 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20200917_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='Staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='medicalrecords',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_reference',
            field=models.UUIDField(default=uuid.UUID('b5a7f988-20e5-4470-8775-edefc0fb5c18'), editable=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.UUIDField(default=uuid.UUID('b02e8523-2250-47d5-a97a-6f7e2e5a2577'), editable=False),
        ),
    ]
