# Generated by Django 3.1 on 2020-09-21 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20200918_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='test_id',
            new_name='test_number',
        ),
        migrations.RemoveField(
            model_name='medicalrecords',
            name='med_ref',
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_number',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='med_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='medicalrecords',
            name='med_number',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_number',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
