# Generated by Django 3.1 on 2020-09-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20200921_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_number',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
    ]
