# Generated by Django 3.1 on 2020-09-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_doctor_doctor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_datetime',
            field=models.DateField(),
        ),
    ]
