# Generated by Django 3.1 on 2020-09-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20200923_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='appointment_history',
            field=models.CharField(max_length=50),
        ),
    ]
